# Generated by Django 5.1.7 on 2025-03-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=100)),
                ('death_toll_low', models.IntegerField()),
                ('death_toll_high', models.IntegerField()),
                ('transmission_type', models.CharField(max_length=100)),
                ('regions_affected', models.TextField()),
                ('symptoms', models.TextField()),
                ('impact', models.TextField()),
            ],
        ),
    ]
