# Generated by Django 5.1.7 on 2025-04-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbreaks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('published', models.DateField()),
                ('outbreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbreaks.outbreak')),
            ],
        ),
    ]
