# Generated by Django 5.1.7 on 2025-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbreaks', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
