# Generated by Django 5.1.7 on 2025-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbreaks', '0003_report_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbreak',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
